### ISSUE TITLE
currentLayers is not defined

### ISSUE THREAD

**Issue by Guitouxx** [spite/WebVR-Extension#20]
Hello,

Recently, I have some errors with the WebVR Chrome extention to view the vr examples on threejs.com like the basic one > [threejs.com cubes example](https://threejs.org/examples/#webvr_cubes)

When I click on "ENTER VR", I have an error wich says
`VM396:240 Uncaught ReferenceError: currentLayers is not defined`

So the VREffect cannot display the dual view.
I suppose it is linked to the recent changes #19 because I didn't have this error a few days ago.

Do you have the same problem?
Thank you

**Comment by spite** [comment]
Yes, apologies. I just realised it was an oversight when releasing 1.1.2

It's now fixed on 1.1.3 https://github.com/spite/WebVR-Extension/blob/master/CHANGELOG.md, which I've just pushed to the Chrome Store. Should be updated in the next 60 minutes or so.

Apologies again for the inconvenience, and thanks for reporting the issue!

**Comment by Guitouxx** [comment]
Perfect it fixed the bug.
Thank you for your reactivity and your great work with this extension !
