### ISSUE TITLE
Visual confusion using extension

### ISSUE THREAD

**Issue by ghost** [spite/WebVR-Extension#23]
Hi, this is not critical issue but got confused by cuboid movements in webvr extension tab in web tools. I can see that cuboid turn around axes X and Z swaped with how turn appears to take place on the screen. While there no indication which angle is which in extension that may mean that turn is correct but visually still thinking of cuboid movement. I checked this on webvr examples and sketchfab models, currently just ignoring cuboid visual movement and accept turns as correct if they are same in examples present.

**Comment by spite** [comment]
I'm not sure I follow. The "cuboid" has roughly the dimensions of an HMD, so it's wider than the other tall and deep. Are you sure you're not reading it as being oriented otherwise?

**Comment by ghost** [comment]
I see, so it represens cardboard in fact. I was thinking more about ship or air jet. My mistake.

**Comment by spite** [comment]
Yes, it represents the HMD. But don't worry, because this issue has kicked me to do something I wanted to do for a long time: changing the box by a proper model of an HMD, something like https://twitter.com/thespite/status/817177306171052032

**Comment by ghost** [comment]
Yeah, that will clear any confusion. Thanks for great emulator you building here.
