### ISSUE TITLE
Messy GUI

### ISSUE THREAD

**Issue by ghost** [spite/WebVR-Extension#25]
![image](https://cloud.githubusercontent.com/assets/15012927/22862586/822caae0-f164-11e6-8da4-3017869c8065.png)

Hi, seems buttons and inscriptions moving with window borders may make messy view sometimes.

**Comment by spite** [comment]
Well, that has an easy fix: don't open the extension in landscape mode and with the console also open. 

PRs with UI fixes are welcome!
